/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package qaus

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        assertNotNull("Not null", "app should have a greeting")
    }
}
